// Database types — will be auto-generated by Supabase CLI in Phase 2
// For now, define types manually matching the schema in 04_C4_Architecture.md

export interface Client {
    id: string;
    name: string;
    logo_url: string | null;
    industry: string | null;
    description: string | null;
    is_featured: boolean;
    display_order: number;
    created_at: string;
}

export interface CaseStudy {
    id: string;
    client_id: string;
    title: string;
    slug: string;
    summary: string | null;
    content: string | null;
    tags: string[];
    service_area: string | null;
    published: boolean;
    created_at: string;
}

export interface Product {
    id: string;
    name: string;
    slug: string;
    short_description: string | null;
    full_description: string | null;
    category: "power-bi-visual" | "tool" | "template";
    appsource_url: string | null;
    demo_url: string | null;
    docs_url: string | null;
    screenshot_urls: string[];
    is_featured: boolean;
    display_order: number;
    created_at: string;
}

export interface ProductClient {
    product_id: string;
    client_id: string;
}

export interface CGAPCohort {
    id: string;
    cohort_number: number;
    year: number | null;
    graduates_count: number | null;
    description: string | null;
    created_at: string;
}

export interface CGAPAlumni {
    id: string;
    cohort_id: string;
    name: string;
    role_after: string | null;
    company_after: string | null;
    quote: string | null;
    photo_url: string | null;
    linkedin_url: string | null;
    is_featured: boolean;
    created_at: string;
}

export interface ContactSubmission {
    id: string;
    name: string;
    email: string;
    company: string | null;
    subject: string | null;
    message: string | null;
    status: "new" | "read" | "responded";
    created_at: string;
}

export interface PartnerEnquiry {
    id: string;
    company: string;
    contact_name: string;
    email: string;
    partnership_type: "technology" | "delivery" | "referral";
    message: string | null;
    status: string;
    created_at: string;
}
