-- ============================================================================
-- Custom Visuals — dynamic content table (admin-managed)
-- Mirrors the case_studies pattern: public reads published rows, writes are
-- service-role only (admin portal uses the service-role client).
-- Run this whole file once in the Supabase SQL editor.
-- ============================================================================

create table if not exists public.custom_visuals (
    id              uuid primary key default gen_random_uuid(),
    slug            text not null unique,
    name            text not null,
    pitch           text,
    features_short  text[] not null default '{}',
    description     text[] not null default '{}',
    features_full   text[] not null default '{}',
    upcoming        text[] not null default '{}',
    -- '#' is the placeholder sentinel: the public page hides the Download button
    -- until a real AppSource URL is set.
    app_source_url  text not null default '#',
    tutorial_url    text,
    preview_src     text,
    display_order   integer not null default 0,
    published       boolean not null default true,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create index if not exists custom_visuals_display_order_idx
    on public.custom_visuals (display_order);

-- keep updated_at fresh
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists custom_visuals_set_updated_at on public.custom_visuals;
create trigger custom_visuals_set_updated_at
    before update on public.custom_visuals
    for each row execute function public.set_updated_at();

-- ── Row Level Security ──────────────────────────────────────────────────────
alter table public.custom_visuals enable row level security;

drop policy if exists "Public reads published custom visuals" on public.custom_visuals;
create policy "Public reads published custom visuals"
    on public.custom_visuals for select
    using (published = true);
-- (service-role bypasses RLS, so the admin portal can read drafts + write.)

-- ── Seed: the 12 existing visuals ───────────────────────────────────────────
insert into public.custom_visuals
  (slug, name, pitch, features_short, description, features_full, upcoming, app_source_url, tutorial_url, preview_src, display_order, published)
values
  ('dual-axis-bar-column-chart', 'Dual Axis Bar & Column Chart', 'Plot two measures on independent scales without dropping in a separate combo chart.', ARRAY['Independent left & right axes', 'Small multiples + conditional colours', 'Native cross-filtering & drill-down']::text[], ARRAY['Dual Axis Bar & Column Chart lets you plot two measures with different scales side by side on independent axes. Switch between horizontal bar and vertical column orientations with a single toggle. Ideal for comparing values like Revenue vs Units Sold, Sales vs Quantity, or Budget vs Actual across categories.', 'The visual supports small multiples for trellis layouts, conditional color formatting with rules and field values, bar patterns for accessibility, overlapping and lipstick bar layouts via bar offset, and dual reference lines. Full Power BI interactivity includes cross-filtering, drill-down, drill-through, report page tooltips, and context menus working natively.', 'All formatting controls use Power BI’s native formatting pane with nested groups, Font Control composites for font family, size, bold, italic, and underline, display units, decimal places, and color pickers. Each axis, legend, bar series, data label, and reference line can be configured independently.']::text[], ARRAY['Dual independent axes with horizontal (bar) and vertical (column) orientation', 'Small multiples, conditional colors, bar patterns, and overlapping bar layouts', 'Cross-filtering, drill-down, drill-through, and report page tooltips', 'Data labels, dual reference lines, and advanced sorting', 'Native formatting pane with per-axis font, color, display units, and decimal places', 'Legend with separate title and values controls, 6 position options']::text[], ARRAY['Error Bars', 'Advanced Multilevel Sorting', 'Axis Scales e.g. Log, Linear, Exponential']::text[], 'https://marketplace.microsoft.com/en-us/product/convergentbusinesstechnologies1681574339335.cbt_dual_axis_bar_and_column_chart?tab=Overview', 'https://www.youtube.com/watch?v=RqJGw6cajgI', '/cbt-custom-visuals/dual-axis-bar-column-chart.png', 10, true),
  ('hierarchical-kpi-cards-tree', 'Dual Hierarchy Decomposition Tree', 'Up to four KPIs per card across two hierarchy axes, with DAX-driven status colours.', ARRAY['Two-axis hierarchy, multi-level drill', 'Up to 4 measures per card', 'DAX-driven traffic-light status']::text[], ARRAY['Dual Hierarchy Decomposition Tree displays your key performance indicators in an interactive, expandable tree layout that supports two independent hierarchy axes simultaneously.', 'Add fields to Hierarchy 1 (Horizontal) to expand cards to the right — for example, by Region or Department. Add fields to Hierarchy 2 (Vertical) to expand cards downward — for example, by Category and Product. Use one axis or both together for matrix-style analysis across two dimensions.', 'Each card displays up to 4 KPI measures side by side: revenue, target percentage, year-over-year growth, status text, or any DAX measure you choose. Numeric values aggregate correctly on parent nodes using Power BI’s native subtotal engine, and percentage or ratio measures use DAX-evaluated totals rather than simple averages. String measures such as status text also display correctly at every aggregation level.', 'The colored status bar at the top of each card can be driven by a DAX measure returning hex color codes, enabling traffic-light indicators, threshold-based coloring, or any custom business logic — evaluated independently at every node in the tree.', 'Format each KPI slot independently with its own font, size, color, display units, and decimal places, or apply a single global style to all values. Customize card dimensions, gaps, title formatting, label formatting, background colors, and border colors from the standard Power BI format pane.', 'Navigate large trees with Ctrl+scroll zoom, click-drag panning, fit-to-page, and a built-in zoom toolbar.']::text[], ARRAY['Up to 4 KPI measures displayed per card', 'Bi-directional tree layout with horizontal and vertical hierarchy axes', 'DAX-driven status bar color with hex code support', 'Per-slot value formatting: independent font, size, color, display units, and decimal places for each KPI', 'Correct aggregation on parent nodes including ratios, percentages, and string measures', 'Multi-level drill-down on both axes with expand/collapse controls', 'Ctrl+scroll zoom, click-drag pan, fit-to-page, and zoom toolbar', 'Cross-filtering with single-click card selection', 'Native Power BI tooltips with canvas tooltip support', 'Customizable card size, gaps, fonts, colors, and alignment from the format pane']::text[], ARRAY['Conditional Formatting', 'Color Coded Indicators for Values with Threshold', 'Reference Values']::text[], 'https://marketplace.microsoft.com/en-us/product/convergentbusinesstechnologies1681574339335.cbt_hierarchical_kpi_cards_tree_basic?tab=Overview', 'https://www.youtube.com/watch?v=fMjR2sA9ZiQ', '/cbt-custom-visuals/hierarchical-kpi-cards-tree.png', 20, true),
  ('multi-kpi-decomposition-tree', 'Multi KPI Decomposition Tree', 'Decompose up to five measures per node, with stacked bars on every branch.', ARRAY['Up to 5 measures per node', 'Stacked bars at each level', 'Expand / collapse hierarchies in place']::text[], ARRAY['The Multi KPI Decomp Tree is a perfect way to visualize hierarchical data if you have multiple KPIs for each node. The visual currently needs the data in tabular form with the hierarchy flattened out. All the levels (depth) of the visual needs to be flattened out into separate columns and so do the associated KPIs. The sample.pbix on the Microsoft AppSource contains the format of the data to use with the visual.']::text[], ARRAY['Stacked Bar Chart option within nodes', 'Up to 5 KPIs within nodes', 'Multiple Formatting Options for the visual', 'Cross Filtering', 'Zooming and Panning']::text[], ARRAY['Search functionality', 'Images on nodes', 'Simple view on zooming out']::text[], 'https://marketplace.microsoft.com/en-us/product/power-bi-visuals/convergentbusinesstechnologies1681574339335.cbt_mutikpi_decomtree_v01?tab=overview', NULL, '/cbt-custom-visuals/multi-kpi-decomposition-tree.png', 30, true),
  ('arabic-matrix-table', 'Arabic Matrix Table', 'Right-to-left matrix with Arabic labels, hierarchical rows, subtotals and grand totals.', ARRAY['Native RTL layout & numerals', 'Multi-level row & column hierarchies', 'Subtotals + grand totals']::text[], ARRAY['The visual enables clear comparison of hierarchical data across rows and columns while fully supporting Arabic layouts, number units, and labeling. It integrates seamlessly with Power BI, offering subtotals, grand totals, cross-filtering, drill-down, tooltips, and flexible customization — making it ideal for financial, operational, and KPI analysis in Arabic dashboards.']::text[], ARRAY['Right-to-Left Arrangement & Aggregation', 'Arabic Data Labels & Number Units', 'Row & Column Hierarchies with Drill-Down', 'Subtotals & Grand Totals', 'Cross Filtration', 'Tooltips', 'Customization Settings']::text[], ARRAY['Conditional Formatting']::text[], 'https://marketplace.microsoft.com/en-us/product/convergentbusinesstechnologies1681574339335.arabic_matrix_table?tab=Overview', 'https://www.youtube.com/watch?v=TCukldoSK7I', '/cbt-custom-visuals/arabic-matrix-table.png', 40, true),
  ('arabic-stacked-bar-chart', 'Arabic Stacked Bar Chart', 'RTL-native stacked bars with Arabic number units, small multiples and cross-filtering.', ARRAY['RTL axis & data labels', 'Arabic number units', 'Small multiples + cross-filtering']::text[], ARRAY['The visual integrates seamlessly with Power BI, offering tooltips, cross-filtering, and flexible customization, making it ideal for financial, operational, and KPI analysis in Arabic dashboards. The sample.pbix on the Microsoft AppSource contains the format of the data to use with the visual.']::text[], ARRAY['Right to Left Arrangement & Aggregation', 'Data Labels & Number Units in Arabic', 'Optional Legends in Arabic', 'Small Multiples', 'Cross Filtration', 'Tooltips', 'Customization settings']::text[], ARRAY['Drilldown into subcategories']::text[], 'https://marketplace.microsoft.com/en-us/product/convergentbusinesstechnologies1681574339335.arabic_stacked_bar_chart?tab=Overview', 'https://www.youtube.com/watch?v=5vBZt-VxP5c', '/cbt-custom-visuals/arabic-stacked-bar-chart.png', 50, true),
  ('arabic-stacked-column-chart', 'Arabic Stacked Column Chart', 'RTL-native stacked columns matched to the Arabic Bar visual for consistent dashboards.', ARRAY['RTL axis & data labels', 'Visual parity with the Bar variant', 'Small multiples + cross-filtering']::text[], ARRAY['The visual integrates seamlessly with Power BI, offering tooltips, cross-filtering, and flexible customization, making it ideal for financial, operational, and KPI analysis in Arabic dashboards. The sample.pbix on the Microsoft AppSource contains the format of the data to use with the visual.']::text[], ARRAY['Right to Left Arrangement & Aggregation', 'Data Labels & Number Units in Arabic', 'Optional Legends in Arabic', 'Small Multiples', 'Cross Filtration', 'Tooltips', 'Customization settings']::text[], ARRAY['Drilldown into subcategories']::text[], 'https://marketplace.microsoft.com/en-us/product/convergentbusinesstechnologies1681574339335.cbt_arabic_stacked_column_chart?tab=Overview', 'https://www.youtube.com/watch?v=G77leg-i5NU', '/cbt-custom-visuals/arabic-stacked-column-chart.png', 60, true),
  ('arabic-waterfall-chart', 'Arabic Waterfall Chart', 'Sequential value walk for Arabic dashboards — variance, build-up and bridge analyses.', ARRAY['RTL value walk', 'Custom positive / negative / total colours', 'Tooltip & cross-filter support']::text[], ARRAY['Waterfall Chart is a custom Power BI visual designed specifically for Arabic and Right-to-Left (RTL) reporting. It enables clear analysis of sequential value changes while fully supporting Arabic layouts, number units, and labeling.', 'The visual integrates seamlessly with Power BI, offering tooltips, cross-filtering, and flexible customization, making it ideal for financial, operational, and KPI analysis in Arabic dashboards. The sample.pbix on the Microsoft AppSource contains the format of the data to use with the visual.']::text[], ARRAY['Right to Left Arrangement & Aggregation', 'Data Labels & Number Units in Arabic', 'Optional Legends in Arabic', 'Cross Filtration', 'Tooltips', 'Customization settings']::text[], ARRAY['Drilldown into subcategories', 'Adding initial offset']::text[], 'https://marketplace.microsoft.com/en-us/product/convergentbusinesstechnologies1681574339335.cbt_arabic_eaterfall_chart?tab=Overview', 'https://youtu.be/BGHl9nKVOXw?si=GSaeN-L1mxt5nFMl', '/cbt-custom-visuals/arabic-waterfall-chart.png', 70, true),
  ('dumbbell-chart', 'Dumbbell Chart', 'Two markers per category on a shared scale, connected by a line that makes the gap immediately visible.', ARRAY['Two markers + connecting gap line per category', 'Currency / % aware labels with directional triangles', 'Conditional colours, reference bands & small multiples']::text[], ARRAY['Business analysts often need to highlight the variance between two related values across categories — the gender pay gap across departments, revenue with and without incentives, or pricing before and after discount. Standard bar and line charts struggle to bring out this picture clearly when both values share an axis. Dumbbell Chart places two markers per category on a shared scale, connected by a line that makes the gap immediately visible — turning raw numbers into an intuitive story of change.', 'The visual recognises currency and percentage formats directly from your data model, so axis and data labels display the correct symbols without manual configuration. Change labels show the difference between the two values as an absolute number, a percentage, or both — with optional directional triangle indicators that instantly communicate whether the movement is positive or negative.', 'Conditional color formatting highlights categories that meet specific thresholds independently for each marker series, using numeric rules or field-value mapping. Unlimited reference bands mark target zones or acceptable ranges behind the data, and four marker shapes with full styling control ensure accessibility and brand alignment. Small multiples split the chart into a trellis grid for side-by-side comparison across segments, with orientation-aware axis coupling and range matching. Full Power BI interactivity is built in — cross-filtering, drill-down, drill-through, report page tooltips and context menus all work natively.']::text[], ARRAY['Two markers per category on a shared scale, joined by a gap-revealing line', 'Currency and percentage format detection directly from the data model', 'Change labels: absolute, percentage, or both — with directional triangle indicators', 'Per-series conditional color formatting via numeric rules or field-value mapping', 'Unlimited reference bands for target zones and acceptable ranges', 'Four marker shapes with full styling control', 'Small multiples with orientation-aware axis coupling and range matching', 'Cross-filtering, drill-down, drill-through, report-page tooltips, context menus']::text[], ARRAY[]::text[], 'https://marketplace.microsoft.com/en-us/product/convergentbusinesstechnologies1681574339335.cbt_dumbbell_plot?tab=Overview', 'https://www.youtube.com/watch?v=yHVr0TildU0', '/cbt-custom-visuals/dumbbell-chart.png', 80, true),
  ('counts-plot', 'Counts Plot', 'Visualise data distribution with dots scaled by frequency across category lanes.', ARRAY['Dots scaled to frequency with auto or manual binning', 'Category swim lanes for side-by-side comparison', 'Conditional colours, reference bands & small multiples']::text[], ARRAY['Analysts working with survey scores, quality metrics, or performance ratings often need to see how values distribute across categories — not just averages, but where the data clusters and where outliers sit. Standard bar charts collapse this detail into single aggregates, hiding the shape of the underlying data. Counts Plot solves this by placing dots along a value axis within category lanes, scaling each dot proportionally to the number of observations at that position. Larger circles mean more data points, making frequency patterns immediately visible.', 'The visual automatically bins nearby values so overlapping data points merge into a single scaled dot rather than stacking invisibly. Users can fine-tune the bin width or leave it on auto for intelligent defaults. A pre-aggregated Count field is also supported for datasets that arrive already summarised.', 'Currency and percentage formats are detected automatically from the data model. Conditional color formatting with numeric rules or field-value mapping highlights thresholds across the distribution. Unlimited reference bands mark target zones, gridlines, reference lines, and a configurable axis range provide full analytical control. Small multiples split the chart into a trellis grid for side-by-side distribution comparison across segments. Cross-filtering, drill-down, drill-through, report page tooltips, and context menus all work natively.']::text[], ARRAY['Dots scaled proportionally to data frequency with automatic or manual binning', 'Category swim lanes for side-by-side distribution comparison across groups', 'Optional Count field for pre-aggregated datasets or auto-count from row-level data', 'Currency and percentage formatting detected automatically from the data model', 'Conditional color formatting with numeric rules or field-value mapping', 'Configurable axis range with minimum and maximum controls', 'Unlimited reference bands with color, opacity, labels, and font formatting', 'Small multiples with axis coupling and range matching', 'Cross-filtering, drill-down, drill-through, report page tooltips, and context menus']::text[], ARRAY[]::text[], '#', 'https://www.youtube.com/watch?v=ydftFNvCG4U', '/cbt-custom-visuals/counts-plot.png', 90, true),
  ('jitter-plot', 'Jitter Plot', 'Show every data point with jitter or beeswarm layout for distribution analysis.', ARRAY['Every observation as an individual dot per lane', 'Jitter and beeswarm layout modes', 'Conditional colours, reference bands & small multiples']::text[], ARRAY['When analysts need to see every individual data point rather than aggregated summaries, standard charts fall short. Box plots show quartiles but hide the raw data. Bar charts reduce distributions to single values. Jitter Plot reveals the full picture by drawing every observation as a dot, spread within category lanes using randomized jitter or tight beeswarm packing so that overlapping points become visible instead of hidden.', 'Two layout modes serve different analytical needs. Jitter mode applies a controlled random offset perpendicular to the value axis, creating a scatter cloud where density is visible through dot clustering. Beeswarm mode uses force-directed packing to position dots as close to the center line as possible without overlap, producing a violin-like shape that reveals distribution contours precisely.', 'Currency and percentage formats are detected automatically from the data model. Conditional color formatting highlights individual data points that meet specific thresholds. Unlimited reference bands mark target zones, and a configurable axis range with minimum and maximum controls provides precise scale management. Small multiples split the chart into a trellis grid for cross-segment comparison. Cross-filtering, drill-down, drill-through, report page tooltips, and context menus all work natively.']::text[], ARRAY['Every data point rendered as an individual dot within category swim lanes', 'Two layout modes: Jitter (random spread) and Beeswarm (force-packed, no overlap)', 'Adjustable jitter amount and beeswarm padding for density control', 'Currency and percentage formatting detected automatically from the data model', 'Conditional color formatting with numeric rules or field-value mapping', 'Configurable axis range with minimum and maximum controls', 'Unlimited reference bands with color, opacity, labels, and font formatting', 'Small multiples with axis coupling and range matching', 'Cross-filtering, drill-down, drill-through, report page tooltips, and context menus']::text[], ARRAY[]::text[], 'https://marketplace.microsoft.com/en-us/product/convergentbusinesstechnologies1681574339335.cbt_jitter_plot?tab=Overview', 'https://www.youtube.com/watch?v=pQvJTKzuzlY', '/cbt-custom-visuals/jitter-plot.png', 100, true),
  ('auto-single-select-slicer', 'Auto Single Select Slicer', 'Smart Power BI slicer with automatic first-value selection — reports never load with an empty filter.', ARRAY['Auto-selects the first value on load', 'Compact dropdown, single-select only', 'Selection persists through filter updates']::text[], ARRAY['Business users frequently work with reports where slicers need a meaningful default state instead of starting empty. Users often need the first available value selected automatically so reports always have a valid filter context on load. Traditional slicers require manual interaction and can create inconsistent report experiences, especially when filters change dynamically.', 'Auto Single Select Slicer solves this by introducing intelligent automatic selection behavior. In Single Select mode, the visual automatically selects the first available value on initial load and maintains a valid selection even when filters affect available values — ensuring reports never have an empty or null filter context.', 'The visual uses a compact Dropdown layout, integrating cleanly into any report canvas without consuming excessive space. It supports Power BI interactions such as cross filtering and maintains the selection dynamically when connected visuals update the available dataset.', 'Formatting options such as font size, bold, italic, underline, padding, borders, background colors, and styling behaviors apply consistently across all slicer elements. The visual integrates naturally with Power BI and improves report usability by eliminating repetitive manual selection while keeping the interface simple and focused.']::text[], ARRAY['Auto-select first value on load for Single Select mode', 'Dropdown layout with compact, clean interface', 'Single Select mode with dropdown-only selection', 'Selection persistence after filtering updates', 'Custom slicer header with title, font color, and show summary', 'Dynamic summary display for the selected value', 'Background, font, border, and padding customization', 'Bold, italic, and underline support across all slicer elements', 'Cross-filtering and slicer-to-slicer interaction support', 'Responsive behavior with Power BI native interactions', 'User-friendly formatting pane configuration']::text[], ARRAY[]::text[], '#', 'https://www.youtube.com/watch?v=rzIxm5B7hcI', '/cbt-custom-visuals/auto-single-select-slicer.png', 110, true),
  ('autoselect-slicer', 'AutoSelect Slicer', 'Smart Power BI slicer with automatic selection across single-select and multi-select scenarios.', ARRAY['Auto-select first value or all values on load', 'Dropdown, List, and Tile layouts', 'Single and multi-select with Select All']::text[], ARRAY['Business users frequently work with reports where slicers need a meaningful default state instead of starting empty. Users often need the first available value selected automatically, or all values selected initially depending on reporting requirements. Traditional slicers require manual interaction and can create inconsistent report experiences, especially when filters change dynamically.', 'AutoSelect Slicer solves this problem by introducing intelligent automatic selection behavior. In Single Select mode, the visual can automatically select the first available value on initial load and maintain a valid selection even when filters affect available values. In Multi Select mode, users can optionally autoselect all values during initial load for a complete dataset view.', 'The visual supports Dropdown, List, and Tile layouts with rich formatting options and customizable behavior. A custom slicer header includes title text, font styling, color settings, and summary display options. The visual supports Power BI interactions such as cross-filtering and maintains selections dynamically when connected visuals update the available dataset.', 'Formatting options such as font size, bold, italic, underline, padding, borders, background colors, and styling behaviors apply consistently across all slicer elements. The visual integrates naturally with Power BI and improves report usability by reducing repetitive user interaction while maintaining flexibility.']::text[], ARRAY['Auto-select first value support for Single Select mode', 'AutoSelect all values support for Multi Select mode', 'AutoSelect all values by default', 'Dropdown, List, and Tile layouts', 'Single Select and Multi Select support', 'Select All support with configurable behavior', 'Selection persistence after filtering updates', 'Custom slicer header with title, text, font color, and show summary', 'Dynamic summary display for selected values', 'Background, font, border, and padding customization', 'Bold, italic, and underline support across all visual elements', 'Cross-filtering and slicer-to-slicer interaction support', 'Responsive behavior with Power BI native interactions', 'User-friendly formatting pane configuration']::text[], ARRAY[]::text[], '#', 'https://www.youtube.com/watch?v=YUEjf1_zqzY', '/cbt-custom-visuals/autoselect-slicer.png', 120, true);
